CREATE ROLE ENTP_OPSCHD_RAW_1_USER_ROLE;
CREATE USER ENTP_OPSCHD_RAW_1_ADMIN IDENTIFIED BY ENTP_OPSCHD_RAW_1_ADMIN737;
GRANT ENTP_OPSCHD_RAW_1_USER_ROLE TO ENTP_OPSCHD_RAW_1_ADMIN;
GRANT RESOURCE TO ENTP_OPSCHD_RAW_1_ADMIN;
GRANT ALL TO ENTP_OPSCHD_RAW_1_ADMIN;
ALTER USER ENTP_OPSCHD_RAW_1_ADMIN ADMIN TRUE;
