CREATE TABLE IF NOT EXISTS OPSCHD_RAW_EVNT (EVENT_MESSAGE_ID VARCHAR2(36) NOT NULL,
CREATE_TIMESTAMP TIMESTAMP(6), MESSAGE_TEXT CLOB, DOMAIN_CODE VARCHAR2(20),
EVENT_TYPE VARCHAR2(32), EVENT_SUB_TYPE VARCHAR(32), ENTITY_ID VARCHAR2(40),
CONSTRAINT XPKOPSCHD_RAW_EVNT PRIMARY KEY (EVENT_MESSAGE_ID ));
CREATE UNIQUE INDEX IF NOT EXISTS XPKOPSCHD_RAW_EVNT ON OPSCHD_RAW_EVNT (EVENT_MESSAGE_ID ASC);